<link rel="icon" type="image/png" href="image/dg_flavicon-dom-logo-550x550-NoBackground.png">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("utils.R")
```

<!-- rmarkdown::render_site() -->

```{r}
thumbnail("Talk: Case Conference 9/18/2024", "images/case_conference_20240918.png", "https://bit.ly/cc091824")
thumbnail("Post: Bush-Francis Catatonia Rating Scale", "images/bfcrs_catatonia.png", "post_bfcrs.html")
thumbnail("Post: Capacity", "images/capacity.png", "post_capacity.html")
thumbnail("Talk: Neurobiology of Addiction 10/31/2023", "images/neurobiologyaddiction.png", "https://bit.ly/neurobioaddict")
thumbnail("Talk: Mental Status Exam 10/2/2023", "images/mentalstatusexam.png", "https://bit.ly/mentalstatusexam")
thumbnail("Flashcards: Agitation Psychopharmacology", "images/agitation_psychopharmacology.png", "post_agitation_psychopharmacology.html")
thumbnail("Flashcards: Erikson’s Psychosocial Stages", "images/rod_long_unsplash.png", "post_eriksons_stages.html")
# thumbnail("Flashcards: Psychopharmacology", "images/hal-gatewood-neuron.png","")
# thumbnail("Flashcards: Pharmacology", "images/danilo-alvesd-pill.png", "post_pharmacology_anki.html")
thumbnail("Post: Rookie Researcher", "images/rookieresearcher.png", "post_rookie_researcher.html")
```

```{r}
# To-Do Posts
# 
# * [ ] Diagnoses by Time
# * [ ] Antipsychotics
# * [ ] Clozapine
# * [ ] Pharmacology Flashcards
# * 
# * 
```
