---
title: "Agitation Psychopharmacology"
output:
  html_document:
    toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**[Download Flashcards](flashcards/agitation_psychopharmacology.apkg)** for Anki

## Summary

| Generic         | Brand                  | Route               | Initial Dose | T<sub>max</sub> | Repeat                     | Maximum Daily Dose | Note                                                                                                                                                                                                                                                        |
| --------------- | ---------------------- | ------------------- | ------------- | --------------- | -------------------------- | -------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Risperidone PO  | Risperdal<sup>®</sup>  | Oral                | 2 mg          | 1 hr            | 2 hr                       | 6 mg / 24 hr   |                                                                                                                                                                                                                                                             |
| Olanzapine PO   | Zyprexa<sup>®</sup>    | Oral                | 5–10 mg       | 6 hr            | 2 hr                       | 20 mg / 24 hr  |                                                                                                                                                                                                                                                             |
| Haloperidol PO  | Haldol<sup>®</sup>     | Oral                | 5 mg          | 30–60 min       | 15 min                     | 20 mg / 24 hr  | Likely to cause higher incidence of extrapyramidal side effects than other recommended drugs                                                                                                                                                                |
| Lorazepam       | Ativan<sup>®</sup>     | Oral, Intramuscular | 2 mg          | 20–30 min       | 2 hr                       | 12 mg / 24 hr  |                                                                                                                                                                                                                                                             |
| Ziprasidone IM  | Geodon<sup>®</sup>     | Intramuscular       | 10–20 mg      | 15 min          | 10 mg q2 hr<br><br>20 mg q4 hr | 40 mg / 24 hr  |                                                                                                                                                                                                                                                             |
| Olanzapine IM | Zyprexa<sup>®</sup> | Intramuscular       | 5–10 mg       | 15–45 min       | 20 min                     | 30 mg / 24 hr  |                                                                                                                                                                                                                                                             |
| Aripiprazole IM | Abilify<sup>®</sup>    | Intramuscular       | 9.75 mg       | 1 hr            | 2 hr                       | 30 mg / 24 hr  |                                                                                                                                                                                                                                                             |
| Haloperidol IM  | Haldol<sup>®</sup>     | Intramuscular       | 5 mg          | 30–60 min       | 15 min                     | 20 mg / 24 hr  | Likely to cause higher incidence of extrapyramidal side effects than other recommended drugs                                                                                                                                                                |
| Haloperidol IV  | Haldol<sup>®</sup>     | Intravenous         | 2–5 mg        | Immediate       | 4 hr                       | 10 mg / 24 hr  | Administering haloperidol intravenously increases risk of QT prolongation.<br><br>Avoid if possible, especially in patients w/ borderline QT or taking other medication that can prolong QT.<br><br>If given IV, limit dose and provide cardiac monitoring. |

## References

* Wilson, M. P. <a href="https://doi.org/10.5811/westjem.2011.9.6866">The Psychopharmacology of Agitation: Consensus Statement of the American Association for Emergency Psychiatry Project BETA Psychopharmacology Workgroup</a> (2012)

* Benajah, N. <a href="https://unsplash.com/photos/mans-face-with-white-scarf-5_gku5Usbzk">Man’s Face with White Scarf</a> (2020)
